import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Script } from "node:vm";
import { build, transform } from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const check = process.argv.includes("--check");
assert(process.argv.slice(2).every(arg => arg === "--check"), "Usage: npm run build -- [--check]");

const source = await readFile(resolve(root, "native-patch/native_patch.source.js"), "utf8");
const sourceHash = createHash("sha256").update(source.replace(/\r\n/g, "\n")).digest("hex");
const compiled = await transform(source, {
  target: "es2020", minifyWhitespace: true, minifySyntax: true, legalComments: "inline",
});
const cli = resolve(dirname(require.resolve("@tailwindcss/cli/package.json")), "dist/index.mjs");
const css = execFileSync(process.execPath, [cli, "--input", "native-patch/tailwind.css", "--minify", "--silent"], {
  cwd: root,
  encoding: "utf8",
  windowsHide: true,
}).trim();
const rules = css.replace(/\/\*[\s\S]*?\*\//g, "");
assert(!/@property|:root|:host|(?:^|[{},])\s*\*(?=[\s,:.{])/.test(rules),
  "Tailwind must stay component-local: use cq: utilities without global theme/property initializers.");

const vendor = await build({
  absWorkingDir: root,
  entryPoints: ["native-patch/ui-libraries.js"],
  bundle: true,
  write: false,
  format: "iife",
  globalName: "__codexQuotaLibraries",
  platform: "browser",
  target: "es2020",
  minify: true,
  legalComments: "inline",
  define: { "process.env.NODE_ENV": '"production"' },
});
const licenseFiles = [
  "tailwindcss/LICENSE",
  "lucide/LICENSE",
  "motion/LICENSE.md",
  "motion-dom/LICENSE.md",
  "motion-utils/LICENSE.md",
  "framer-motion/LICENSE.md",
];
const licenses = await Promise.all(licenseFiles.map(file => readFile(resolve(root, "node_modules", file), "utf8")));
const notices = [...new Set(licenses.map(text => text.trim()))].join("\n\n---\n\n");
const output = `// Generated by npm run build. Edit native-patch/native_patch.source.js instead.\n` +
  `// Source SHA-256: ${sourceHash}\n` +
  `/*! Bundled UI library licenses\n${notices}\n*/\n` +
  `(() => {\n${vendor.outputFiles[0].text}\n` +
  `const __codexQuotaTailwindCss = ${JSON.stringify(css)};\n` +
  `return ${compiled.code.trim()}\n})()\n`;
new Script(output, { filename: "native_patch.js" });

for (const file of ["native-patch/native_patch.js", "skills/codex-usage-card/assets/native-patch/native_patch.js"]) {
  const path = resolve(root, file);
  if (check) {
    assert.equal((await readFile(path, "utf8")) === output, true, `${file} is stale; run npm run build.`);
  } else {
    await writeFile(path, output, "utf8");
  }
}
console.log(`${check ? "Verified" : "Built"} both native_patch.js copies (${Buffer.byteLength(output)} bytes; Tailwind ${Buffer.byteLength(css)} bytes).`);
